openapi: 3.0.3
info:
  title: Swagger Meddix - Meddix com e-Ship 
  description: |
    Esta é a API do Meddix, um sistema de integração desenvolvido pela ACABIT COMÉRCIO E TECNOLOGIA LTDA. Através desta API, é possível realizar diversas operações, como consulta de produtos ativos, atualização de lotes de produtos, consulta de produção interna por status e atualização de status de solicitações no Meddix.
    
    Alguns links úteis:
    - [Site Acabit](http://acabit.com.br)

    **Observação:** Algumas URIs não têm parâmetros explicitamente definidos na seção de parâmetros, pois os parâmetros estão presentes na própria URI. Por exemplo, em "http://192.168.0.64:8082/lotes/49712", o parâmetro após "/" é o número do lote a ser consultado.
    
     **Leganda:** As legendas para as Strings estão no final do documento.

  contact:
    email: suporte@acabit.com
  version: 3.0.0
servers:
  - url: https://iploja:porta
tags:
  - name: produtos
    description: Operações relacionadas a produtos
  - name: lotes
    description: Operações relacionadas a lotes de produtos
  - name: solicitacoes
    description: Operações relacionadas a solicitações
  - name: cliente
    description: Operações relacionadas a clientes
  - name: veiculos
    description: Operações relacionadas a veículos
  - name: requisicao
    description: Operações relacionadas a requisições
paths:
  /cid:
    get:
      summary: Consulta informações do CID
      tags:
        - requisicao
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo_cid:
                    type: string
                    maxLength: 5
                    description: Código do CID
                  descricao:
                    type: string
                    maxLength: 500
                    description: Descrição do CID
                  tipouso:
                    type: integer
                    enum: [0, 1, 2]
                    description: Tipo de uso (0-Interno, 1-Externo, 2-Ambos)
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: "Bad request"
  /veiculos:
    get:
      summary: Consulta informações dos veículos
      tags:
        - veiculos
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  veiculos:
                    type: array
                    items:
                      type: object
                      properties:
                        id_veiculo:
                          type: integer
                          description: ID do veículo
                        tipouso:
                          type: integer
                          enum: [0, 1, 2]
                          description: Tipo de uso (0-Interno, 1-Externo, 2-Ambos)
                        descricao:
                          type: string
                          description: Descrição do veículo
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: "Bad request"

  /veiculostipo:
    get:
      summary: Consulta informações do tipo de veículos
      tags:
        - veiculos
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  tiposveiculos:
                    type: array
                    items:
                      type: object
                      properties:
                        id_tipo:
                          type: integer
                          description: ID do tipo de veículo
                        descricao:
                          type: string
                          description: Descrição do tipo de veículo
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: "Bad request"

  /cliente:
    get:
      summary: Consulta informações do cliente
      tags:
        - cliente
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  cpfcnpj:
                    type: string
                    description: CPF ou CNPJ do cliente
                  idclienteweb:
                    type: integer
                    description: ID do cliente web
                  sexo:
                    type: string
                    enum: ["M", "F"]
                    description: Sexo do cliente
                  inscricaoestadualrg:
                    type: string
                    description: Inscrição estadual ou RG
                  nascimento:
                    type: string
                    format: date
                    description: Data de nascimento
                  nome:
                    type: string
                    description: Nome do cliente
                  sobrenome:
                    type: string
                    description: Sobrenome do cliente
                  email:
                    type: string
                    description: Email do cliente
                  endereco:
                    type: string
                    description: Endereço do cliente
                  numero:
                    type: string
                    description: Número do endereço
                  complemento:
                    type: string
                    description: Complemento do endereço
                  bairro:
                    type: string
                    description: Bairro
                  cidade:
                    type: string
                    description: Cidade
                  uf:
                    type: string
                    description: UF
                  cep:
                    type: string
                    description: CEP
                  foneresidencial:
                    type: string
                    description: Telefone residencial
                  fonecomercial:
                    type: string
                    description: Telefone comercial
                  celular:
                    type: string
                    description: Celular
                  fax:
                    type: string
                    description: Fax
                  doctipo:
                    type: integer
                    description: Tipo do documento
                  docorgexped:
                    type: integer
                    description: Órgão expedidor
                  docuf:
                    type: string
                    description: UF do documento
                  celoperadora:
                    type: string
                    description: Operadora do celular
                  celular2:
                    type: string
                    description: Celular 2
                  celoperadora2:
                    type: string
                    description: Operadora do celular 2
                  whatsapp:
                    type: string
                    description: WhatsApp
                  tipoempresa:
                    type: integer
                    description: Tipo de empresa
                  inscricaomunicipal:
                    type: string
                    description: Inscrição municipal
                  destinacao:
                    type: integer
                    description: Tipo de destinação da venda
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: "Bad request"
  /produtos:
    get:
      summary: Consulta a lista de produtos ativos no Meddix
      tags:
        - produtos
      parameters:
        - name: codigoproduto
          in: query
          description: Código do produto
          required: false
          schema:
            type: string
        - name: grupo
          in: query
          description: Grupos de produtos (A = Acabado D = Drogaria E = Embalagem M = Matéria prima O = Outros R= Revenda S = Semi Acabados)
          required: false
          schema:
            type: string
            enum: [A, D, E, M, O, R, S]
        - name: tipodiluicao
          in: query
          description: Tipo de diluição do produto 0 = Puro 1 = Diluído
          required: false
          schema:
            type: string
            enum: ["0", "1"]
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  produtos:
                    type: array
                    items:
                      type: object
                      properties:
                        codigoproduto:
                          type: string
                          description: Código do produto
                        codigobarras:
                          type: string
                          description: Código de barras do produto
                        descricao:
                          type: string
                          description: Descrição do produto
                        nomecodificado:
                          type: string
                          description: Nome codificado do produto
                        grupo:
                          type: string
                          description: Grupo do produto
                        unidade:
                          type: string
                          description: Unidade do produto
                        diluicao:
                          type: string
                          description: Tipo de diluição do produto
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: "Bad request"
  /sinonimos:
    get:
      summary: Consulta os sinônimos dos produtos
      tags:
        - produtos
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_produto:
                      type: integer
                      description: ID do produto
                    id_sinonimo:
                      type: integer
                      description: ID do sinonimo
                    descricao:
                      type: string
                      description: Descrição do sinônimo
                    
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: Bad request
  /lotes/{codigoproduto}:
    get:
      summary: Consulta a lista de lotes de um produto no Meddix
      tags:
        - lotes
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  lotes:
                    type: array
                    items:
                      type: object
                      properties:
                        filiallote:
                          type: string
                          description: Filial do lote
                        idlote:
                          type: integer
                          description: ID do lote
                        codigolote:
                          type: string
                          description: Código do lote
                        numerolote:
                          type: string
                          description: Número do lote
                        disponivel:
                          type: number
                          description: Quantidade disponível do lote
                        reservado:
                          type: number
                          description: Quantidade reservada do lote
                        precocusto:
                          type: number
                          description: Preço de custo do lote
                        fabricacao:
                          type: string
                          format: date
                          description: Data de fabricação do lote
                        validade:
                          type: string
                          format: date
                          description: Data de validade do lote
                        notafiscal:
                          type: string
                          description: Número da nota fiscal
                        fornecedor:
                          type: string
                          description: Fornecedor do lote
                        diluicao:
                          type: string
                          description: Tipo de diluição do lote
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: "Bad request"
    post:
      summary: Atualiza a lista de lotes produtos no Meddix
      tags:
        - lotes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lotes:
                  type: array
                  items:
                    type: object
                    properties:
                      diluicao:
                        type: string
                        description: Diluição
                      filiallote:
                        type: string
                        description: Filial do lote
                      idlote:
                        type: integer
                        description: ID do lote
                      quantidade:
                        type: integer
                        description: Quantidade
                      tipo:
                        type: integer
                        description: Tipo
              example:
                lotes:
                  - diluicao: "0"
                    filiallote: "001"
                    idlote: 23011
                    quantidade: 1
                    tipo: 2
                  - diluicao: "0"
                    filiallote: "001"
                    idlote: 23011
                    quantidade: 1
                    tipo: 1
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de retorno
                    example: 200
                  motivo:
                    type: string
                    description: Motivo do retorno
                    example: "Sucesso"
        '400':
          description: Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de erro
                    example: 400
                  motivo:
                    type: string
                    description: Motivo do erro
                    example: "Bad request"

  /solicitacoes/{status}/status:
    get:
      summary: Consulta produção interna por status
      tags:
        - solicitacoes
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: integer
                    description: Código de retorno
                    example:
